#!/bin/bash

python3 -m venv venv
source venv/bin/activate
pip install -r requrements.txt

cd src
python manage.py migrate
python manage.py collectstatic

cd ..
python scripts/import_dataset.py
python scripts/index_marqo.py