#!/bin/bash

python3 -m venv venv
source venv/bin/activate
pip install -r requirements.txt

python src/manage.py migrate
python src/manage.py collectstatic

# Skip the Dataset import since it takes so much timme
# python scripts/import_dataset.py
python scripts/index_marqo.py